/**
 *
 * $Id$
 */
package gmf_relational_model.gmf_relational_model.validation;

import gmf_relational_model.gmf_relational_model.EGenericType;
import gmf_relational_model.gmf_relational_model.LinkFK;
import gmf_relational_model.gmf_relational_model.Relation;

/**
 * A sample validator interface for {@link gmf_relational_model.gmf_relational_model.Attribute}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttributeValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateType(EGenericType value);
	boolean validatePkReference(Relation value);
	boolean validateIsFK(LinkFK value);
	boolean validateIsUN(boolean value);
	boolean validateIsNN(boolean value);
	boolean validateIsContained(Relation value);
	boolean validateLabelWidth(int value);
	boolean validateIsPK(boolean value);
}
